adding components
hahays/portfolio pull request #1
Opened 2022-03-10 04:02 UTC by hahays

2022-03-16 19:54 UTC, vkhalikov requested changes
Я не увидел ни одного компонента, который ты бы переиспользовал. Пропадает смысл использования реакта.

Пока что вот такие замечания, как пройдёшься по ним, будем дальше смотреть.

Дополнительно:
1) Зачем кучу шрифтов poppins установил? Все используешь?
2) Некоторые изображения дублируются в `src/images` и `src/assets/{ComponentName}`. Можно держать все изображения в `src/assets/images`. Также можно положить изображение в папку компонента, если оно нужно только там.
3) Не понравилась структура файлов компонентов. Почему все компоненты внутри компонента `PortfolioContainer`. Лучше создать папки containers и components. Такая древовидная структура может очень быстро стать сложной. Она удобна для роутинга, а для компонентов - нет.

2022-03-16 19:54 UTC, vkhalikov commented on l-resume/package.json
> +  "homepage": "https://hahays.github.io/portfolio/",
Убрать ненужную папку `l-resume`

2022-03-16 19:54 UTC, vkhalikov commented on l-resume/public/index.html
> +      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
ты же вроде устанавливал font-awesome как npm-пакет, зачем ещё тут?

2022-03-16 19:54 UTC, vkhalikov commented on l-resume/public/index.html
> +      href="db.onlinewebfonts.com/c/157c6cc36dd65b1b2adc9e7f3329c761?family=Amazon+Ember"
Проверить, подгружается ли шрифт

2022-03-16 19:54 UTC, vkhalikov commented on l-resume/src/App.css
> +  --light-blue : #04C3FF;
css переменные, очень хорошо

2022-03-16 19:54 UTC, vkhalikov commented on l-resume/src/App.js
> +      <ToastContainer />
Где используется? Если не используется, то зачем оно?

2022-03-16 19:54 UTC, vkhalikov commented on l-resume/src/PortfolioContainer/ContactMe/ContactMe.css
> +form p {
Не стоит использовать селекторы тэгов. У тебя потом любой параграф внутри формы получит эти стили.

2022-03-16 19:54 UTC, vkhalikov commented on l-resume/src/PortfolioContainer/ContactMe/ContactMe.js
> +import load1 from "../../../src/images/load2.gif";
Лучше сделать через элемент, как обсуждали :)

2022-03-16 19:54 UTC, vkhalikov commented on l-resume/src/PortfolioContainer/Footer/Footer.css
> +    .social-icon:hover {
Всё криво, используй prettier

2022-03-16 19:54 UTC, vkhalikov commented on l-resume/src/index.css
> +.btn {
Не стоит такое держать в основном css-файле. Лучше сделать отдельный компонент-кнопку.

2022-03-16 19:54 UTC, vkhalikov commented on l-resume/src/reportWebVitals.js
> +const reportWebVitals = (onPerfEntry) => {
Какие результаты? :)

2022-03-16 19:54 UTC, vkhalikov commented on l-resume/src/utilities/Animations.js
> +  static animations = new Animations();
Сам писал? Если да, то зачем тут синглтон? Почему просто новый экземпляр через new не создавать?

2022-03-16 19:54 UTC, vkhalikov commented on l-resume/src/utilities/ScreenHeading/ScreenHeading.js
> +        <div></div>
Тут точно нужен пустой див?
Может быть, можно такой конструкцией обойтись?

```
props.subHeading && (
  <div className="screen-sub-heading">
    <span>{props.subHeading}</span>
  </div>
)
```

2022-03-16 19:54 UTC, vkhalikov commented on l-resume/src/utilities/ScrollService.js
> +  static scrollHandler = new ScrollSerivce();
И тут тоже куча синглтонов.

2022-03-16 19:54 UTC, vkhalikov commented on l-resume/src/utilities/commonUtilis.css
> +nav {
Почему это в папке утилит?
Больше похоже на простой css, который следует разместить в компоненте `Navigation`, например.

2022-03-16 19:54 UTC, vkhalikov commented on l-resume/src/PortfolioContainer/PortfolioContaier.js
> +  const mapAllScreens = () => {
Эта функция не зависит от пропсов, можно вынести за пределы компонента.

2022-03-16 19:54 UTC, vkhalikov commented on l-resume/src/PortfolioContainer/PortfolioContaier.js
> +        <div key={screen.screen_name}></div>
Зачем тут этот пустой див? Можно же просто ничего не рендерить.
Но у тебя же все элементы в `TOTAL_SCREENS` всё равно все имеют `screen_name`.

Ну и вообще, если так подумать, то зачем тебе тут этот маппинг? Почему нельзя просто отрендерить компоненты `Home, Resume ContactMe`:

```
<Home />
<Resume />
<ContactMe />
```

2022-03-16 19:57 UTC, vkhalikov commented on l-resume/src/App.css
> +  --light-blue : #04C3FF;
Жаль только, использовать не стал :))))

2022-03-18 05:49 UTC, hahays commented on l-resume/src/reportWebVitals.js
> +const reportWebVitals = (onPerfEntry) => {
x) 
убрал

2022-03-18 09:53 UTC, hahays commented on l-resume/src/utilities/commonUtilis.css
> +nav {
создал отдельный компонент Navigation с двумя файлами: Navigation.js и navigation.css

2022-03-18 10:01 UTC, hahays commented on l-resume/public/index.html
> +      href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css"
Все верно подметил, удалил не используемые линки

2022-03-18 10:08 UTC, hahays commented on l-resume/public/index.html
> +      href="db.onlinewebfonts.com/c/157c6cc36dd65b1b2adc9e7f3329c761?family=Amazon+Ember"
проверил, теперь подгружается

2022-03-28 09:58 UTC, hahays commented on l-resume/src/App.css
> +  --light-blue : #04C3FF;
Ахах) Изначально использовал все, пока Попов не сказал что ужасные, детские цвета)) подредактировал css в каждом компоненте, теперь используются только цвета записанные в переменные в руте.

2022-03-31 01:52 UTC, hahays commented on l-resume/src/App.js
> +      <ToastContainer />
Хотел использовать в дальнейшем, но вот после твоего вопроса этого - просто удалил. . .

2022-03-31 01:57 UTC, hahays commented on l-resume/src/PortfolioContainer/ContactMe/ContactMe.css
> +form p {
Поправил

2022-03-31 02:01 UTC, hahays commented on l-resume/src/PortfolioContainer/Footer/Footer.css
> +    .social-icon:hover {
Сделал, использовал  *Pettier

* Игра слов prettier и petite

2022-03-31 02:39 UTC, hahays commented on l-resume/src/index.css
> +.btn {
Согласен, отдельную компонент-кнопку создавать не стал, цсс добавил в компонент где используется кнопка

2022-03-31 02:56 UTC, hahays commented on l-resume/src/utilities/Animations.js
> +  static animations = new Animations();
К сожалению, именно это делал по уроку

2022-03-31 03:01 UTC, hahays commented on l-resume/src/utilities/ScreenHeading/ScreenHeading.js
> +        <div></div>
Он бы и быть так, но теперь его там нет. . .

2022-03-31 03:02 UTC, hahays commented on l-resume/src/utilities/ScrollService.js
> +  static scrollHandler = new ScrollSerivce();
Мне сам термин нравится, неужели это плохо?

2022-03-31 03:13 UTC, hahays commented on l-resume/src/PortfolioContainer/PortfolioContaier.js
> +  const mapAllScreens = () => {
сделала

2022-03-31 04:54 UTC, hahays commented on l-resume/src/utilities/Animations.js
> +  static animations = new Animations();
сделал

2022-04-02 11:42 UTC, hahays commented on l-resume/package.json
> +    "gh-pages": "^3.2.3",
добавила

2022-04-02 11:59 UTC, vkhalikov commented on l-resume/src/PortfolioContainer/Footer/Footer.css
> +    .social-icon:hover {
Тхахаха, pettitier xDDD

2022-04-02 14:51 UTC, vkhalikov requested changes
Со структурой получше стало. Смотришь в `App.js` - сразу видно отдельные элементы. Правда с файловой структурой ещё остались недоработки, до сих пор древовидная структура компонентов.
Начал переиспользовать компоненты, отлично. Продолжай в том же духе.
Вернулись css-переменные - плюс.

Остальное в комментах.

P.S. Не дай Поппи-сану себя догнать :)

2022-04-02 14:51 UTC, vkhalikov commented on l-resume/src/components/Navigation/Navigation.js
> +    let classes = "header-option ";
Для манипуляций с классовыми именами есть классная утилита - 'classnames'.
Кстати, не вижу, чтобы у тебя эта функция использовалась.

2022-04-02 14:51 UTC, vkhalikov commented on l-resume/src/containers/ContactMe/ContactMe.js
> +  const [bool, setBool] = useState(false);
Что ещё за `bool`? Не понятно из названия за что отвечает. Ну все остальные же хорошо назвал.

2022-04-02 14:51 UTC, vkhalikov commented on l-resume/src/containers/Resume/Resume.js
> +  const Projectss = ({ image, title, description, source, live }) => {
Это ошибка. Нельзя объявлять компоненты внутри компонентов. Они будут перерендериваться каждый раз.
У нас в приложении тоже такая проблема есть, я даже писал насчёт этого мини-статью, но она для внутреннего использования, я не знаю как её расшарить.
В общем, это нужно обсудить.

2022-04-02 14:51 UTC, vkhalikov commented on l-resume/src/containers/Resume/Resume.js
> +const Resume = (props) => {
Очень громоздкий компоненты вышел. Внутри ещё доп компоненты и константы создаются (я ранее писал, что стоит выносить из компонента то, что не зависит от пропсов).
Нужно стремиться к тому, чтобы код был как можно более читабельным для других, приходит с опытом :)
Тут мне тяжело разбираться, что происходит. Постарайся упростить, вынести лишне, разбить на более мелкие компоненты.

2022-04-02 14:51 UTC, vkhalikov commented on l-resume/src/utilities/ScrollService.js
> +  static scrollHandler = new ScrollSerivce();
Я просто не понимаю, зачем он здесь нужен :)

2022-04-02 14:51 UTC, vkhalikov commented on l-resume/src/containers/Resume/Resume.js
> +  const projectsDetails = [
Вот здесь отлично, вынес данные в константы, а дальше в компоненте уже описываешь, как это отрендерить.

2022-04-02 14:51 UTC, vkhalikov commented on l-resume/src/containers/Resume/Resume.js
> +  const resumeDetails = [
Почему это в массив завёрнуто?

2022-04-02 14:51 UTC, vkhalikov commented on l-resume/src/containers/Resume/Resume.css
> +.highlighted-btn {
Ну вот посмотри, ты и тут кнопками стили задаёшь и в `Profile.css`. Дублирование. А если ещё в 10 компонентов кнопки добавишь, там снова для них будешь css писать?
А теперь представь, что тебе нужно поменять внешний вид кнопок. Будешь по всему коду бегать, прыгать, искать, где у тебя для них стили задаются и менять везде. Потом ещё окажется, что пропустил где-то и останется одинокая кнопка, выбивающаяся из общего стиля.
А теперь представь, что кнопка сделана компонентом. Ты зашёл в файл этого компонента. В ОДИН ФАЙЛ! Поменял несколько строчек, и все кнопки разом стали выглядеть так, как тебе нужно. Очень просто.

Поэтому ты зря отказался выносить кнопку в компонент. Наоборот, такие вещи, как кнопки, инпуты, всевозможные ui-элементы нужно в первую очередь делать компонентами. Это строительные блоки для других компонентов и всего приложения. Мельчайшие кирпичики, которые используются чаще всего.

2022-04-02 14:51 UTC, vkhalikov commented on l-resume/src/containers/Footer/Footer.js
> +  let socialDetails = [
Не зависит от пропсов. Константа. Вынеси за компонент.

2022-04-04 02:04 UTC, hahays commented on l-resume/public/index.html
> +      href="db.onlinewebfonts.com/c/157c6cc36dd65b1b2adc9e7f3329c761?family=Amazon+Ember"
не знаю, братик, у меня подгружается
![amazon](https://user-images.githubusercontent.com/57741608/161462210-d1d4bc80-1320-479e-8132-a0cec44aef56.png)

2022-04-04 02:08 UTC, hahays commented on l-resume/package.json
> +    "gh-pages": "^3.2.3"
Да, но хотел убедиться, что и ты ознакомился))

2022-04-04 02:45 UTC, hahays commented on l-resume/src/PortfolioContainer/PortfolioContaier.js
> +const PortfolioContainer = () => {
Кто-то видимо восстановил файл, потому что как только я перестал его использовать и создал отдельные компоненты - я сразу его удалил. . . Будем разбираться кто это сделал. . .

2022-04-04 07:11 UTC, hahays commented on l-resume/src/components/Navigation/Navigation.js
> +    let classes = "header-option ";
Да, поправил) Это вот то самое, о чем говорил в телеге, что не успел до конца функционал навибара доделать

2022-04-04 07:48 UTC, hahays commented on l-resume/src/containers/Resume/Resume.js
> +  const resumeDetails = [
Исправила

2022-04-05 02:09 UTC, hahays commented on l-resume/src/PortfolioContainer/PortfolioContaier.js
> +        <div key={screen.screen_name}></div>
Сделало

2022-04-05 06:53 UTC, hahays commented on l-resume/src/containers/Resume/Resume.js
> +const Resume = (props) => {
Понял о чём ты, брат, переделал этот компонент, добавил 2 новых контейнера, немножко убрал лишнее и убрал наконец вторую 's' с projects, мозолила глаз уже две недели)

2022-04-05 09:10 UTC, hahays commented on l-resume/src/containers/Resume/Resume.css
> +.highlighted-btn {
Да, согласен, сейчас потратил много времени, пытаясь найти нужный мне стиль. . . Создал отдельный компонент - Button

2022-04-05 09:18 UTC, hahays commented on l-resume/src/containers/Footer/Footer.js
> +  let socialDetails = [
done

2022-04-08 10:07 UTC, closed without merging